#!/usr/bin/env python3
"""Assemble a deployable Wallpaper Engine folder:  dist/<id>/  =  wallpapers/<id>/src/  +  shared modules  +  generated data.

usage: build.py <wallpaper-id> [--no-bundle-data]
  --no-bundle-data   public-release build: no bundled snapshot and no history seed (the wallpaper starts empty and
                     fetches with the user's own key), only the creator colour table.

The manifest wallpapers/<id>/wallpaper.json says which shared modules to copy (into dist/<id>/js/<basename>) and
which data feeds to bundle (data/aa/<feed>/ -> js/history-seed.js, data/cosmos-data.js)."""
import json, shutil, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "aa"))
ROOT = ROOT.parent

def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args: sys.exit(__doc__)
    wid, bundle = args[0], "--no-bundle-data" not in sys.argv
    wdir = ROOT / "wallpapers" / wid
    manifest = json.load(open(wdir / "wallpaper.json", encoding="utf-8"))
    out = ROOT / "dist" / wid
    if out.exists(): shutil.rmtree(out)
    shutil.copytree(wdir / "src", out)
    (out / "js").mkdir(exist_ok=True)
    for rel in manifest.get("shared", []):
        shutil.copy2(ROOT / "shared" / rel, out / "js" / Path(rel).name)
    data = manifest.get("data", {})
    if data.get("creator_colors"):
        colors = {k: v["color"] for k, v in json.load(open(ROOT / "shared" / "aa" / "creator-colors.json", encoding="utf-8"))["creators"].items()}
        (out / "js" / "creator-colors.js").write_text("// generated by tools/build.py from shared/aa/creator-colors.json — AA chart colours only, null = unknown\nwindow.AA_CREATOR_COLORS = " + json.dumps(colors, ensure_ascii=False) + ";\n", encoding="utf-8")
    seed_feed = data.get("history_seed") if bundle else None
    if seed_feed == "aa/language":
        import export_cosmos as CE
        colors = {k: {"color": v["color"]} for k, v in json.load(open(ROOT / "shared" / "aa" / "creator-colors.json", encoding="utf-8"))["creators"].items()}
        seed = []
        for fetched_at, d in CE.list_snapshots():
            meta, pages = CE.load_snapshot(d)
            models, _, _, _ = CE.normalise(pages, meta["fetched_at"], colors)
            seed.append({"t": meta["fetched_at"], "m": {m["id"]: [m["rank_intelligence"], m["intelligence"]] for m in models},
                         "f": {m["family_key"]: m["rank_intelligence_family"] for m in models if m["is_family_best"]}})
        (out / "js" / "history-seed.js").write_text("// generated by tools/build.py — compact REAL snapshots used as rank-change baselines until the wallpaper has its own history\nwindow.AA_HISTORY_SEED = " + json.dumps(seed, separators=(",", ":")) + ";\n", encoding="utf-8")
    else:
        (out / "js" / "history-seed.js").write_text("window.AA_HISTORY_SEED = [];\n", encoding="utf-8")
    snap_feed = data.get("bundle_snapshot") if bundle else None
    (out / "data").mkdir(exist_ok=True)
    if snap_feed == "aa/language":
        doc = json.load(open(ROOT / "data" / "aa" / "language" / "cosmos-data.json", encoding="utf-8"))
        (out / "data" / "cosmos-data.js").write_text("// generated by tools/build.py from data/aa/language/cosmos-data.json — bundled real snapshot, shown until live data arrives\nwindow.COSMOS_DATA_BUNDLED = " + json.dumps(doc, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")
    else:
        (out / "data" / "cosmos-data.js").write_text("// no bundled snapshot in this build: the wallpaper fetches with the user's key\n", encoding="utf-8")
    total = 0
    for f in sorted(out.rglob("*")):
        if f.is_file(): total += f.stat().st_size; print(f"  {f.relative_to(out).as_posix():28s} {f.stat().st_size / 1024:7.0f} KB")
    print(f"built dist/{wid} ({total / 1024:.0f} KB, {'bundled data' if bundle else 'no bundled data'}) -> deploy folder '{manifest['deploy_folder']}'")

if __name__ == "__main__":
    main()
